package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnnouncementToUser generated by hbm2java
 */
@Entity
@Table(name = "announcement_to_user", catalog = "mydb1")
public class AnnouncementToUser implements java.io.Serializable {

	private Integer id;
	private Announcement announcement;
	private User user;
	private Boolean ischecked;

	public AnnouncementToUser() {
	}

	public AnnouncementToUser(Announcement announcement) {
		this.announcement = announcement;
	}

	public AnnouncementToUser(Announcement announcement, User user, Boolean ischecked) {
		this.announcement = announcement;
		this.user = user;
		this.ischecked = ischecked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "announcementid", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "touser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "ischecked")
	public Boolean getIschecked() {
		return this.ischecked;
	}

	public void setIschecked(Boolean ischecked) {
		this.ischecked = ischecked;
	}

}
