package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attitude generated by hbm2java
 */
@Entity
@Table(name = "attitude", catalog = "mydb1")
public class Attitude implements java.io.Serializable {

	private Integer attitudeid;
	private String attname;
	private Integer mark;
	private Set<StudentHasAttitude> studentHasAttitudes = new HashSet<StudentHasAttitude>(0);

	public Attitude() {
	}

	public Attitude(String attname, Integer mark, Set<StudentHasAttitude> studentHasAttitudes) {
		this.attname = attname;
		this.mark = mark;
		this.studentHasAttitudes = studentHasAttitudes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attitudeid", unique = true, nullable = false)
	public Integer getAttitudeid() {
		return this.attitudeid;
	}

	public void setAttitudeid(Integer attitudeid) {
		this.attitudeid = attitudeid;
	}

	@Column(name = "attname", length = 100)
	public String getAttname() {
		return this.attname;
	}

	public void setAttname(String attname) {
		this.attname = attname;
	}

	@Column(name = "mark")
	public Integer getMark() {
		return this.mark;
	}

	public void setMark(Integer mark) {
		this.mark = mark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attitude")
	public Set<StudentHasAttitude> getStudentHasAttitudes() {
		return this.studentHasAttitudes;
	}

	public void setStudentHasAttitudes(Set<StudentHasAttitude> studentHasAttitudes) {
		this.studentHasAttitudes = studentHasAttitudes;
	}

}
