package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassroomHasEmployee generated by hbm2java
 */
@Entity
@Table(name = "classroom_has_employee", catalog = "mydb1")
public class ClassroomHasEmployee implements java.io.Serializable {

	private Integer id;
	private Classroom classroom;
	private Employee employee;
	private String schoolyear;
	private Integer semester;

	public ClassroomHasEmployee() {
	}

	public ClassroomHasEmployee(Classroom classroom, Employee employee) {
		this.classroom = classroom;
		this.employee = employee;
	}

	public ClassroomHasEmployee(Classroom classroom, Employee employee, String schoolyear, Integer semester) {
		this.classroom = classroom;
		this.employee = employee;
		this.schoolyear = schoolyear;
		this.semester = semester;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classid", nullable = false)
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeerid", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "schoolyear", length = 45)
	public String getSchoolyear() {
		return this.schoolyear;
	}

	public void setSchoolyear(String schoolyear) {
		this.schoolyear = schoolyear;
	}

	@Column(name = "semester")
	public Integer getSemester() {
		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

}
