package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassroomHasTeacher generated by hbm2java
 */
@Entity
@Table(name = "classroom_has_teacher", catalog = "mydb1")
public class ClassroomHasTeacher implements java.io.Serializable {

	private Integer id;
	private Classroom classroom;
	private Subject subject;
	private Teacher teacher;
	private String schoolyear;
	private Integer semester;

	public ClassroomHasTeacher() {
	}

	public ClassroomHasTeacher(Classroom classroom, Teacher teacher) {
		this.classroom = classroom;
		this.teacher = teacher;
	}

	public ClassroomHasTeacher(Classroom classroom, Subject subject, Teacher teacher, String schoolyear,
			Integer semester) {
		this.classroom = classroom;
		this.subject = subject;
		this.teacher = teacher;
		this.schoolyear = schoolyear;
		this.semester = semester;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classid", nullable = false)
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subjectid")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacherid", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "schoolyear", length = 45)
	public String getSchoolyear() {
		return this.schoolyear;
	}

	public void setSchoolyear(String schoolyear) {
		this.schoolyear = schoolyear;
	}

	@Column(name = "semester")
	public Integer getSemester() {
		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

}
