package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.RollCallJsonView;
import com.hendisantika.jwt.jsonview.TeacherJsonView;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "mydb1")
public class Employee implements java.io.Serializable {

	@JsonView(TeacherJsonView.Public.class)
	private Integer employeerid;
	private User user;
	@JsonView({ RollCallJsonView.Public.class, TeacherJsonView.Public.class })
	private String employeename;
	@JsonView(TeacherJsonView.Public.class)
	private Date birthday;
	private Set<ClassroomHasEmployee> classroomHasEmployees = new HashSet<ClassroomHasEmployee>(0);
	private Set<Rollcall> rollcalls = new HashSet<Rollcall>(0);

	public Employee() {
	}

	public Employee(User user, String employeename, Date birthday, Set<ClassroomHasEmployee> classroomHasEmployees,
			Set<Rollcall> rollcalls) {
		this.user = user;
		this.employeename = employeename;
		this.birthday = birthday;
		this.classroomHasEmployees = classroomHasEmployees;
		this.rollcalls = rollcalls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "employeerid", unique = true, nullable = false)
	public Integer getEmployeerid() {
		return this.employeerid;
	}

	public void setEmployeerid(Integer employeerid) {
		this.employeerid = employeerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "employeename", length = 45)
	public String getEmployeename() {
		return this.employeename;
	}

	public void setEmployeename(String employeename) {
		this.employeename = employeename;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<ClassroomHasEmployee> getClassroomHasEmployees() {
		return this.classroomHasEmployees;
	}

	public void setClassroomHasEmployees(Set<ClassroomHasEmployee> classroomHasEmployees) {
		this.classroomHasEmployees = classroomHasEmployees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Rollcall> getRollcalls() {
		return this.rollcalls;
	}

	public void setRollcalls(Set<Rollcall> rollcalls) {
		this.rollcalls = rollcalls;
	}

}
