package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.MarkJsonView;

/**
 * Mark generated by hbm2java
 */
@Entity
@Table(name = "mark", catalog = "mydb1")
public class Mark implements java.io.Serializable {

	@JsonView(MarkJsonView.Public.class)
	private Integer markid;
	@JsonView(MarkJsonView.Public.class)
	private Student student;
	@JsonView(MarkJsonView.Public.class)
	private Teacher teacher;
	@JsonView(MarkJsonView.Public.class)
	private Test test;
	@JsonView(MarkJsonView.Public.class)
	private Float value;
	@JsonView(MarkJsonView.Public.class)
	private String schoolyear;
	@JsonView(MarkJsonView.Public.class)
	private Integer semester;
	@JsonView(MarkJsonView.Public.class)
	private Date date;

	public Mark() {
	}

	public Mark(Student student, Test test) {
		this.student = student;
		this.test = test;
	}

	public Mark(Student student, Teacher teacher, Test test, Float value, String schoolyear, Integer semester,
			Date date) {
		this.student = student;
		this.teacher = teacher;
		this.test = test;
		this.value = value;
		this.schoolyear = schoolyear;
		this.semester = semester;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "markid", unique = true, nullable = false)
	public Integer getMarkid() {
		return this.markid;
	}

	public void setMarkid(Integer markid) {
		this.markid = markid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentid", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacherid")
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testid", nullable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@Column(name = "value", precision = 12, scale = 0)
	public Float getValue() {
		return this.value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

	@Column(name = "schoolyear", length = 45)
	public String getSchoolyear() {
		return this.schoolyear;
	}

	public void setSchoolyear(String schoolyear) {
		this.schoolyear = schoolyear;
	}

	@Column(name = "semester")
	public Integer getSemester() {
		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
