package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.ClassHasStudentJsonView;
import com.hendisantika.jwt.jsonview.MarkJsonView;
import com.hendisantika.jwt.jsonview.RollCallJsonView;
import com.hendisantika.jwt.jsonview.StudentsOfClassJsonView;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "mydb1")
public class Student implements java.io.Serializable {

	@JsonView({ StudentsOfClassJsonView.Public.class, ClassHasStudentJsonView.Public.class })
	private Integer studentid;
	private User user;
	@JsonView({ StudentsOfClassJsonView.Public.class, RollCallJsonView.Public.class, MarkJsonView.Public.class,
			ClassHasStudentJsonView.Public.class })
	private String studentname;
	@JsonView({ StudentsOfClassJsonView.Public.class, ClassHasStudentJsonView.Public.class })
	private Date birthday;
	@JsonView(StudentsOfClassJsonView.Public.class)
	private Set<Classroom> classrooms = new HashSet<Classroom>(0);

	private Set<StudentHasAttitude> studentHasAttitudes = new HashSet<StudentHasAttitude>(0);
	private Set<Rollcall> rollcalls = new HashSet<Rollcall>(0);
	private Set<Mark> marks = new HashSet<Mark>(0);

	public Student() {
	}

	public Student(User user, String studentname, Date birthday, Set<Classroom> classrooms,
			Set<StudentHasAttitude> studentHasAttitudes, Set<Rollcall> rollcalls, Set<Mark> marks) {
		this.user = user;
		this.studentname = studentname;
		this.birthday = birthday;
		this.classrooms = classrooms;
		this.studentHasAttitudes = studentHasAttitudes;
		this.rollcalls = rollcalls;
		this.marks = marks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "studentid", unique = true, nullable = false)
	public Integer getStudentid() {
		return this.studentid;
	}

	public void setStudentid(Integer studentid) {
		this.studentid = studentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "studentname", length = 45)
	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<Classroom> getClassrooms() {
		return this.classrooms;
	}

	public void setClassrooms(Set<Classroom> classrooms) {
		this.classrooms = classrooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudentHasAttitude> getStudentHasAttitudes() {
		return this.studentHasAttitudes;
	}

	public void setStudentHasAttitudes(Set<StudentHasAttitude> studentHasAttitudes) {
		this.studentHasAttitudes = studentHasAttitudes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Rollcall> getRollcalls() {
		return this.rollcalls;
	}

	public void setRollcalls(Set<Rollcall> rollcalls) {
		this.rollcalls = rollcalls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Mark> getMarks() {
		return this.marks;
	}

	public void setMarks(Set<Mark> marks) {
		this.marks = marks;
	}

}
