package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentHasAttitude generated by hbm2java
 */
@Entity
@Table(name = "student_has_attitude", catalog = "mydb1")
public class StudentHasAttitude implements java.io.Serializable {

	private Integer id;
	private Attitude attitude;
	private Student student;
	private Teacher teacher;
	private Integer count;
	private String date;

	public StudentHasAttitude() {
	}

	public StudentHasAttitude(Attitude attitude, Student student) {
		this.attitude = attitude;
		this.student = student;
	}

	public StudentHasAttitude(Attitude attitude, Student student, Teacher teacher, Integer count, String date) {
		this.attitude = attitude;
		this.student = student;
		this.teacher = teacher;
		this.count = count;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attitude_attitudeid", nullable = false)
	public Attitude getAttitude() {
		return this.attitude;
	}

	public void setAttitude(Attitude attitude) {
		this.attitude = attitude;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_studentid", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacherid")
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "date", length = 45)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
