package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.MarkJsonView;
import com.hendisantika.jwt.jsonview.TeacherJsonView;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "mydb1")
public class Teacher implements java.io.Serializable {

	@JsonView(TeacherJsonView.Public.class)
	private Integer teacherid;
	private User user;
	@JsonView({ MarkJsonView.Public.class, TeacherJsonView.Public.class })
	private String teachername;
	@JsonView(TeacherJsonView.Public.class)
	private Date birthday;
	private Set<StudentHasAttitude> studentHasAttitudes = new HashSet<StudentHasAttitude>(0);
	private Set<Subject> subjects = new HashSet<Subject>(0);
	private Set<ClassroomHasTeacher> classroomHasTeachers = new HashSet<ClassroomHasTeacher>(0);
	private Set<Mark> marks = new HashSet<Mark>(0);

	public Teacher() {
	}

	public Teacher(User user, String teachername, Date birthday, Set<StudentHasAttitude> studentHasAttitudes,
			Set<Subject> subjects, Set<ClassroomHasTeacher> classroomHasTeachers, Set<Mark> marks) {
		this.user = user;
		this.teachername = teachername;
		this.birthday = birthday;
		this.studentHasAttitudes = studentHasAttitudes;
		this.subjects = subjects;
		this.classroomHasTeachers = classroomHasTeachers;
		this.marks = marks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "teacherid", unique = true, nullable = false)
	public Integer getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "teachername", length = 45)
	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<StudentHasAttitude> getStudentHasAttitudes() {
		return this.studentHasAttitudes;
	}

	public void setStudentHasAttitudes(Set<StudentHasAttitude> studentHasAttitudes) {
		this.studentHasAttitudes = studentHasAttitudes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "teacher_has_subject", catalog = "mydb1", joinColumns = {
			@JoinColumn(name = "teacherid", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "subjectid", nullable = false, updatable = false) })
	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<ClassroomHasTeacher> getClassroomHasTeachers() {
		return this.classroomHasTeachers;
	}

	public void setClassroomHasTeachers(Set<ClassroomHasTeacher> classroomHasTeachers) {
		this.classroomHasTeachers = classroomHasTeachers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<Mark> getMarks() {
		return this.marks;
	}

	public void setMarks(Set<Mark> marks) {
		this.marks = marks;
	}

}
