package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.MarkJsonView;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "mydb1")
public class Test implements java.io.Serializable {

	private Integer testid;
	@JsonView(MarkJsonView.Public.class)
	private Subject subject;
	@JsonView(MarkJsonView.Public.class)
	private String testname;
	private Float coef;
	private Set<Mark> marks = new HashSet<Mark>(0);

	public Test() {
	}

	public Test(Subject subject, String testname, Float coef, Set<Mark> marks) {
		this.subject = subject;
		this.testname = testname;
		this.coef = coef;
		this.marks = marks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "testid", unique = true, nullable = false)
	public Integer getTestid() {
		return this.testid;
	}

	public void setTestid(Integer testid) {
		this.testid = testid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subjectid")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "testname", length = 45)
	public String getTestname() {
		return this.testname;
	}

	public void setTestname(String testname) {
		this.testname = testname;
	}

	@Column(name = "coef", precision = 12, scale = 0)
	public Float getCoef() {
		return this.coef;
	}

	public void setCoef(Float coef) {
		this.coef = coef;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	public Set<Mark> getMarks() {
		return this.marks;
	}

	public void setMarks(Set<Mark> marks) {
		this.marks = marks;
	}

}
