package com.hendisantika.jwt.domain;
// Generated Dec 18, 2018 10:00:44 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.hendisantika.jwt.jsonview.UserJsonView;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mydb1")
public class User implements java.io.Serializable {

	@JsonView(UserJsonView.Public.class)
	private Integer id;
	@JsonView(UserJsonView.Public.class)
	private String username;
	@JsonView(UserJsonView.Public.class)
	private String mail;
	@JsonView(UserJsonView.Public.class)
	private String pass;
	@JsonView(UserJsonView.Public.class)
	private String role;
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Announcement> announcements = new HashSet<Announcement>(0);
	private Set<Teacher> teachers = new HashSet<Teacher>(0);
	private Set<AnnouncementToUser> announcementToUsers = new HashSet<AnnouncementToUser>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public User() {
	}

	public User(String username, String mail, String pass, String role, Set<Student> students,
			Set<Announcement> announcements, Set<Teacher> teachers, Set<AnnouncementToUser> announcementToUsers,
			Set<Employee> employees) {
		this.username = username;
		this.mail = mail;
		this.pass = pass;
		this.role = role;
		this.students = students;
		this.announcements = announcements;
		this.teachers = teachers;
		this.announcementToUsers = announcementToUsers;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "mail", length = 200)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "pass", length = 200)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Announcement> getAnnouncements() {
		return this.announcements;
	}

	public void setAnnouncements(Set<Announcement> announcements) {
		this.announcements = announcements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<AnnouncementToUser> getAnnouncementToUsers() {
		return this.announcementToUsers;
	}

	public void setAnnouncementToUsers(Set<AnnouncementToUser> announcementToUsers) {
		this.announcementToUsers = announcementToUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
